fos_user:
  db_driver: orm # other valid values are 'mongodb' and 'couchdb'
  firewall_name: main
  user_class: App\Entity\FosUser
  from_email:
    address: "duyquan627@gmail.com"
    sender_name: "test@domain.com"
  registration:
    form:
      type: App\Form\RegistrationFormType